name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # Set up Front-End Wiki repository URLs
          git remote set-url origin --push "https://github.com/CodeCraft-Solutions-DREAM-Lab/Front-End.wiki.git"
          
          # Set up Back-End Wiki repository URLs
          git remote add back_end_wiki "https://github.com/CodeCraft-Solutions-DREAM-Lab/Back-End.wiki.git"
          git remote set-url --push back_end_wiki "https://github.com/CodeCraft-Solutions-DREAM-Lab/Back-End.wiki.git"

      - name: Push to Front-End Wiki
        run: |
          git push -q origin main:master --force

      - name: Push to Back-End Wiki
        run: |
          git push -q origin main:master --force
