name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Push to Front-End Wiki
        run: |
          git push -q "https://github.com/CodeCraft-Solutions-DREAM-Lab/Front-End.wiki.git?token=${{ secrets.GITHUB_TOKEN }}" main:master --force

      - name: Push to Back-End Wiki
        run: |
          git push -q "https://github.com/CodeCraft-Solutions-DREAM-Lab/Back-End.wiki.git?token=${{ secrets.GITHUB_TOKEN }}" main:master --force
